FROM openjdk:11-jre
COPY build/libs/demo-devops-*.jar app.jar
#ENTRYPOINT ["java", "-jar", "app.jar"]
#ENV SPRING_PROFILES_ACTIVE = ${SPRING_PROFILES_ACTIVE}
ENTRYPOINT ["java", "-Dspring.profiles.active=local", "-jar", "app.jar"]