#서버 환경별 설정 분리
spring:
  profiles:
    active: local
server:
  port: 80
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/demodevops?characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    username: demodevops
#    password: demodevops1!23
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    open-in-view: false
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      format_sql: true
#      ddl-auto: create
---
#spring:
#  profiles:
#    active: dev
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://10.0.2.232:3306/demodevops?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    username: demodevops
#    password: demodevops1!23
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    open-in-view: false
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      format_sql: true
#      ddl-auto: create
